### ISSUE TITLE
When run update command, items will be drafted in the web store.

### ISSUE THREAD

**Issue by 1natsu172** [pastak/chrome-webstore-manager#7]
Items are drafted when I use the `update` command. It is for items already published in store. It will behave the same from local or from CI...

##### code

```zsh
WEBSTORE_TOKEN=[TOKEN] chrome-webstore-manager update [ITEM_ID] ./packages/*.zip
```

> bump version to v1.2.8

then

![](https://i.gyazo.com/e470c9a3faa6e728f7a4c57aa0445e7a.png)

I thought that it was unnatural behavior because README has written "Only this command, your items is under draft." So, I asked a this question. Or is this intentional behavior? 🤔

**Comment by pastak** [comment]
This is Chrome WebStore API's behavior. If you want to make new version public, execuse `chrome-webstore-manager publish ITEM_ID`.

**Comment by 1natsu172** [comment]
Thanks for your response.

Hmm, It's normal behavior to draft with `chrome-webstore-manager update`. The question was solved. It was refreshing! I'd like to publish the extension automatically, so I'll run `publish` after `update`.

Thanks for providing a convenient manager 👍
